FROM us-west2-docker.pkg.dev/practical-yew-383010/staging-loopx-base/node-16:latest
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY . .
COPY .env /home/node/app/apps/web/.env.production
#COPY .env .env
#COPY package.json ./
#COPY yarn.lock ./
RUN yarn install && yarn build

#RUN yarn build

EXPOSE 3001

CMD ["yarn", "run" , "start"]
