import styled from 'styled-components'

const Wrapper = styled.div`
  display: flex;
  gap: 64px;
  //   margin-top: -150px;
`

const LeftContent = styled.div``

const RightContent = styled.div`
  .list {
    .icon_stone {
      margin-right: 16px;
    }

    p {
      display: flex;
      margin-bottom: 16px;
      align-items: center;
    }
  }

  .title_list_item {
    font-weight: 400;
    font-size: 18px;
    color: rgba(255, 255, 255, 0.87);
    line-height: 32px;
  }
`

const Title = styled.p`
  font-weight: 700;
  font-size: 36px;
  line-height: 48px;
  color: rgba(255, 255, 255, 0.87);
`

const Paragraph = styled.p`
  font-weight: 400;
  font-size: 18px;
  line-height: 32px;
  color: rgba(255, 255, 255, 0.87);
`

const Watch = styled.div`
  width: 473px;
  height: 100%;
  background: #9072ff;
  border-radius: 24px;
`

const FeatureWatch = () => {
  return (
    <Wrapper>
      <LeftContent>
        <Watch>
          <span> </span>
        </Watch>
      </LeftContent>

      <RightContent>
        <Title>Meet XOXS. Our Hybrid Multichain Stable Coin.</Title>
        <Paragraph style={{ margin: '24px 0' }}>
          Designed to be the staking substitute to our governance token XOX, preventing Supply Inflation & Selling
          Pressure XOXS is the result of months studding how staking works, chart behavior to high APYs followed by high
          selling pressure from stakers and Passive Income strategies generated by implementing Stable Coins Like BUSD,
          USDC .... Some Facts About XOXS:
        </Paragraph>

        <div className="list">
          {listTag.map(({ title }) => {
            return (
              <p>
                <span>
                  <img src="/images/icon-stone.svg" alt="icon-stone" className="icon_stone" />
                </span>
                <span className="title_list_item">{title}</span>
              </p>
            )
          })}
        </div>
      </RightContent>
    </Wrapper>
  )
}

const listTag = [
  {
    title: 'Only acquired by First Buying the governance token XOX then XOXS is received as a bonus. (no extra cost)',
  },
  {
    title: 'Auto staking functionality with a minimum 8% APY',
  },
  {
    title: 'Earned through giveaways, finishing tasks, community activities etc',
  },
  {
    title:
      'Allow users to earn passive income through staking with no risk neither to the holders or the project long term sustainability.',
  },
]

export default FeatureWatch
